### ISSUE TITLE
Add licence to project

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/stem-diverse-android-tv#1]
## Description

As a maintainer,
I need a license to be added to the repository,
so that I can inform potential contributors to the terms and conditions of contributing to the project.

From what I have seen GNU General Public License v3.0 is the license used in most of the projects.
Here's the [mentorship-android project license](https://github.com/anitab-org/mentorship-android/blob/develop/LICENSE).

### Update [Required]
- [ ] Add a license to the project

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
10 min

**Comment by annabauza** [comment]
💯 Thank you!
