### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/stem-diverse-android-tv#10]
## Description
As a contributor,
I need to understand what the project is about and how to setup,
so that I can contribute to it.

I think a first version of the README, should include at least:
- description of the app (mission, objective, etc)
- how to setup, dependencies, version of Android
- communication channel (e.g.: Zulip link and stream dedicated)

### Update [Required]
- [ ] Add a first version of the README

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 min

**Comment by kbhardwaj123** [comment]
@isabelcosta i am interested to implement the docs for this project

**Comment by annabauza** [comment]
@kbhardwaj123 please do I'm happy to review and add suggestions
