### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/stem-diverse-android-tv#2]
## Description
As a contributor,
I need to know how maintainers expect us to contribute,
so that I can understand the procedures I need to follow.

As a context, from what I know there is some general contributing guidelines general to the community. **Not sure if these are going to change in near future.** An example of it is the "general guidelines" on [mentorship-android CONTRIBUTING.md file](https://github.com/anitab-org/mentorship-android/blob/develop/.github/CONTRIBUTING.md). There is also project-specific guidelines,

### Update [Required]
- [ ] Add CONTRIBUTING.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by annabauza** [comment]
💯 approved
