### ISSUE TITLE
Add Bug Report template

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/stem-diverse-android-tv#3]
## Description

As a bug reporter,
I need a template for bug report,
so that I can provide necessary details for a bug.

So contributors can report bugs in the app, it's useful to have a BUG_REPORT template so that contributors can have a guide of how to report a bug.

Here's [an example on mentorship-android](https://github.com/anitab-org/mentorship-android/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) as a guide.

### Update [Required]
- [ ] Add a BUG_REPORT.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 min

**Comment by annabauza** [comment]
💯 approved
